#!/usr/bin/env python3
"""Capture LAB 01 static gate evidence.

The script runs the repository-level static gates and the LAB 01 static gates,
then stores raw stdout/stderr in evidence/lab01_static_gates.txt.
"""

from __future__ import annotations

import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

LAB_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = LAB_ROOT.parents[1]
EVIDENCE = LAB_ROOT / "evidence" / "lab01_static_gates.txt"


@dataclass(frozen=True)
class CommandResult:
    """Result of one subprocess command."""

    name: str
    args: list[str]
    returncode: int
    stdout: str
    stderr: str


def run_command(name: str, args: list[str]) -> CommandResult:
    """Run one gate command from the repository root."""

    completed = subprocess.run(
        args,
        cwd=REPO_ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    return CommandResult(name, args, completed.returncode, completed.stdout, completed.stderr)


def render(results: list[CommandResult]) -> str:
    """Render command results in an audit-friendly plain-text format."""

    lines: list[str] = [
        "# LAB 01 static gates evidence",
        "# Generated by labs/lab01_insecure_vs_hardened/tools/capture_static_gates.py",
        "",
    ]
    for result in results:
        lines.extend(
            [
                f"## {result.name}",
                f"command: {' '.join(result.args)}",
                f"returncode: {result.returncode}",
                "stdout:",
                result.stdout.rstrip() or "<empty>",
                "stderr:",
                result.stderr.rstrip() or "<empty>",
                "",
            ]
        )
    overall = "PASS" if all(result.returncode == 0 for result in results) else "FAIL"
    lines.append(f"# capture_validation result={overall}")
    return "\n".join(lines) + "\n"


def main() -> int:
    """Run gates and write evidence."""

    EVIDENCE.parent.mkdir(parents=True, exist_ok=True)
    results = [
        run_command("repository_static_gates", [sys.executable, str(REPO_ROOT / "tools" / "repo_quality_gates" / "run_static_repo_gates.py")]),
        run_command("lab01_static_gates", [sys.executable, str(LAB_ROOT / "tools" / "run_static_gates.py")]),
    ]
    EVIDENCE.write_text(render(results), encoding="utf-8", newline="\n")
    if any(result.returncode != 0 for result in results):
        print(f"FAIL: static gates evidence written to {EVIDENCE}")
        return 1
    print(f"PASS: static gates evidence written to {EVIDENCE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
