#!/usr/bin/env python3
"""Capture LAB 01 secret-scan evidence for INSECURE and HARDENED logs."""

from __future__ import annotations

import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

LAB_ROOT = Path(__file__).resolve().parents[1]
EVIDENCE_DIR = LAB_ROOT / "evidence"
OUTPUT = EVIDENCE_DIR / "lab01_secret_scan.txt"
CHECKER = LAB_ROOT / "tools" / "check_no_secrets_in_logs.py"


@dataclass(frozen=True)
class ScanCase:
    """One log scanner invocation."""

    name: str
    logfile: Path
    profile: str


CASES = [
    ScanCase("insecure_log_scan", EVIDENCE_DIR / "lab01_insecure_console.log", "insecure"),
    ScanCase("hardened_log_scan", EVIDENCE_DIR / "lab01_hardened_console.log", "hardened"),
]


def run_case(case: ScanCase) -> subprocess.CompletedProcess[str]:
    """Run one log checker invocation."""

    return subprocess.run(
        [sys.executable, str(CHECKER), str(case.logfile), "--profile", case.profile],
        cwd=LAB_ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )


def main() -> int:
    """Run all scans and write raw evidence."""

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# LAB 01 secret scan evidence",
        "# Generated by labs/lab01_insecure_vs_hardened/tools/capture_secret_scan.py",
        "",
    ]
    failed = False
    for case in CASES:
        result = run_case(case)
        failed = failed or result.returncode != 0
        lines.extend(
            [
                f"## {case.name}",
                f"command: {sys.executable} {CHECKER} {case.logfile} --profile {case.profile}",
                f"returncode: {result.returncode}",
                "stdout:",
                result.stdout.rstrip() or "<empty>",
                "stderr:",
                result.stderr.rstrip() or "<empty>",
                "",
            ]
        )
    lines.append(f"# capture_validation result={'FAIL' if failed else 'PASS'}")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    if failed:
        print(f"FAIL: secret scan evidence written to {OUTPUT}")
        return 1
    print(f"PASS: secret scan evidence written to {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
