#!/usr/bin/env python3
"""
Align LAB 03 static-gate contract after the Mosquitto matrix baseline.

This tool is intentionally idempotent. It fixes documentation generated by the
initial LAB 03 tool, hardens static-gate evidence capture, and removes generated
ESP-IDF artifacts before running static gates.
"""

from __future__ import annotations

import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LAB = ROOT / "labs" / "lab03_mqtt_tls"

LEARNING_SECTION = """## Objetivos de aprendizaje

- Entender la diferencia entre MQTT plano, MQTT autenticado, MQTT sobre TLS y MQTT sobre WebSockets.
- Evidenciar por qué MQTT sin TLS no debe considerarse seguro aunque permita conexión funcional.
- Comparar los escenarios publicados por `test.mosquitto.org` en puertos 1883, 1884, 8883, 8884, 8885, 8886, 8887, 8080, 8081, 8090 y 8091.
- Aprender a clasificar cada escenario como `CUMPLE`, `NO CUMPLE`, `NO VALIDADO` o `PENDIENTE` según transporte, autenticación y validación de certificados.
- Generar evidencias reproducibles mediante consola, logs NDJSON y gates estáticos.
"""

CAPTURE_STATIC_GATES = r'''#!/usr/bin/env python3
from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
LAB = ROOT / "labs" / "lab03_mqtt_tls"
OUT = LAB / "evidence" / "lab03_static_gates.txt"


def remove_generated_artifacts() -> None:
    """Remove local ESP-IDF outputs that are forbidden by repository gates."""
    for path in [
        LAB / "firmware" / "build",
        LAB / "firmware" / "sdkconfig",
        LAB / "firmware" / "sdkconfig.old",
    ]:
        if path.is_dir():
            shutil.rmtree(path)
        elif path.exists():
            path.unlink()


def run(command: list[str]) -> tuple[int, str, str]:
    result = subprocess.run(command, cwd=ROOT, text=True, capture_output=True)
    return result.returncode, result.stdout, result.stderr


def file_has_pass(path: Path) -> bool:
    return path.exists() and "capture_validation result=PASS" in path.read_text(
        encoding="utf-8", errors="replace"
    )


def update_evidence_readme(static_ok: bool) -> None:
    evidence_readme = LAB / "evidence" / "README.md"
    console_ok = file_has_pass(LAB / "evidence" / "lab03_m03_1883_console.log")
    console_status = "CUMPLE" if console_ok else "PENDIENTE"
    static_status = "CUMPLE" if static_ok else "PENDIENTE"
    evidence_readme.write_text(
        "\n".join(
            [
                "# Evidencias LAB 03",
                "",
                "## Índice",
                "",
                "- [Propósito](#propósito)",
                "- [Evidencias de fase 03A](#evidencias-de-fase-03a)",
                "- [Pendientes](#pendientes)",
                "",
                "## Propósito",
                "",
                "Este directorio almacena evidencias de ejecución del LAB 03.",
                "",
                "No se deben versionar credenciales reales, certificados privados ni payloads sensibles.",
                "",
                "## Evidencias de fase 03A",
                "",
                "| Fichero | Estado | Descripción |",
                "| --- | --- | --- |",
                f"| `lab03_m03_1883_console.log` | {console_status} | Baseline MQTT 1883 sin TLS. |",
                f"| `lab03_static_gates.txt` | {static_status} | Gates estáticos. |",
                "",
                "## Pendientes",
                "",
                "| Evidencia | Estado |",
                "| --- | --- |",
                "| `lab03_build_esp32s3.txt` | PENDIENTE |",
                "| `lab03_real_broker_matrix.txt` | PENDIENTE |",
                "| `lab03_tls_certificate_validation.txt` | PENDIENTE |",
            ]
        )
        + "\n",
        encoding="utf-8",
        newline="\n",
    )


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    remove_generated_artifacts()

    sections = ["# LAB 03 static gates evidence", ""]
    commands = [
        [sys.executable, "tools/repo_quality_gates/run_static_repo_gates.py"],
        [sys.executable, "labs/lab03_mqtt_tls/tools/run_static_gates.py"],
    ]
    ok = True
    for command in commands:
        rc, stdout, stderr = run(command)
        ok = ok and rc == 0
        sections += [
            "## command",
            " ".join(command),
            f"returncode: {rc}",
            "stdout:",
            stdout.strip() or "<empty>",
            "stderr:",
            stderr.strip() or "<empty>",
            "",
        ]

    sections.append(f"# capture_validation result={'PASS' if ok else 'FAIL'}")
    OUT.write_text("\n".join(sections) + "\n", encoding="utf-8", newline="\n")
    update_evidence_readme(ok)
    print(f"{'PASS' if ok else 'FAIL'}: static gates evidence written to {OUT}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
'''


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8", newline="\n")


def insert_learning_section(text: str) -> str:
    if "## Objetivos de aprendizaje" in text:
        return text
    marker = "\n## Alcance\n"
    if marker in text:
        return text.replace(marker, "\n" + LEARNING_SECTION.rstrip() + "\n" + marker, 1)
    fallback = "\n## Matriz contractual\n"
    if fallback in text:
        return text.replace(fallback, "\n" + LEARNING_SECTION.rstrip() + "\n" + fallback, 1)
    return text.rstrip() + "\n\n" + LEARNING_SECTION


def update_lab_readme() -> None:
    path = LAB / "README.md"
    if not path.exists():
        raise FileNotFoundError(f"missing LAB 03 README: {path}")
    write(path, insert_learning_section(read(path)))


def update_global_readme() -> None:
    path = ROOT / "README.md"
    if not path.exists():
        return
    lines = []
    for line in read(path).splitlines():
        if line.strip().startswith("| LAB 03 |"):
            lines.append("| LAB 03 | Matriz MQTT test.mosquitto.org | EN CURSO |")
        else:
            lines.append(line)
    text = "\n".join(lines)
    text = text.replace(
        "LAB 03+ permanecen como laboratorios pendientes.",
        "LAB 03 está en curso con matriz Mosquitto y baseline 1883 sin TLS; LAB 04+ permanecen pendientes.",
    )
    text = text.replace(
        "LAB 03 permanece como laboratorio pendiente.",
        "LAB 03 está en curso con matriz Mosquitto y baseline 1883 sin TLS.",
    )
    write(path, text)


def update_roadmap() -> None:
    path = ROOT / "ROADMAP.md"
    if not path.exists():
        return
    text = read(path).replace(
        "- [ ] LAB 03 — MQTT seguro con TLS.",
        "- [ ] LAB 03 — Matriz MQTT test.mosquitto.org: 03A baseline 1883 sin TLS en curso.",
    )
    write(path, text)


def update_generator() -> None:
    path = ROOT / "tools" / "maintenance" / "apply_lab03_mosquitto_matrix.py"
    if not path.exists():
        return
    text = read(path)
    text = text.replace("        CONFIG_ESP_CONSOLE_UART_NONE=y\n", "")
    text = insert_learning_section(text)
    old_sections = '["## Índice", "## Objetivo", "## Matriz contractual", "## Cómo compilar", "## Evidencias esperadas", "## Estado"]'
    new_sections = '["## Índice", "## Objetivo", "## Objetivos de aprendizaje", "## Matriz contractual", "## Cómo compilar", "## Evidencias esperadas", "## Estado"]'
    text = text.replace(old_sections, new_sections)
    write(path, text)


def update_firmware_defaults() -> None:
    path = LAB / "firmware" / "sdkconfig.defaults"
    if not path.exists():
        return
    lines = [line for line in read(path).splitlines() if line.strip() != "CONFIG_ESP_CONSOLE_UART_NONE=y"]
    write(path, "\n".join(lines))


def write_capture_static_gates() -> None:
    write(LAB / "tools" / "capture_static_gates.py", CAPTURE_STATIC_GATES)


def update_evidence_readme_initial() -> None:
    # Keep static gates pending here; capture_static_gates.py will update this file after it runs.
    evidence_readme = LAB / "evidence" / "README.md"
    if not evidence_readme.exists():
        return
    console_ok = (LAB / "evidence" / "lab03_m03_1883_console.log").exists() and "capture_validation result=PASS" in read(
        LAB / "evidence" / "lab03_m03_1883_console.log"
    )
    static_ok = (LAB / "evidence" / "lab03_static_gates.txt").exists() and "capture_validation result=PASS" in read(
        LAB / "evidence" / "lab03_static_gates.txt"
    )
    console_status = "CUMPLE" if console_ok else "PENDIENTE"
    static_status = "CUMPLE" if static_ok else "PENDIENTE"
    text = read(evidence_readme)
    text = text.replace("| `lab03_m03_1883_console.log` | PENDIENTE |", f"| `lab03_m03_1883_console.log` | {console_status} |")
    text = text.replace("| `lab03_static_gates.txt` | PENDIENTE |", f"| `lab03_static_gates.txt` | {static_status} |")
    write(evidence_readme, text)


def remove_generated_artifacts() -> None:
    for path in [
        LAB / "firmware" / "build",
        LAB / "firmware" / "sdkconfig",
        LAB / "firmware" / "sdkconfig.old",
    ]:
        if path.is_dir():
            shutil.rmtree(path)
        elif path.exists():
            path.unlink()


def main() -> int:
    update_lab_readme()
    update_global_readme()
    update_roadmap()
    update_generator()
    update_firmware_defaults()
    write_capture_static_gates()
    update_evidence_readme_initial()
    remove_generated_artifacts()
    print("PASS: LAB 03 static-gate alignment applied")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
